spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:9271/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"


management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"