server:
  port: 9202

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: inventory
  application:
    name: "inventory"
  config:
    import: "optional:configserver:http://localhost:9271/"

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9270/eureka/
